{
 "title": "Weather Data Quality Dashboard",
 "time": { "from": "2024-03-01T00:00:00.000Z", "to": "2024-03-27T00:00:00.000Z" },
 "panels": [
  {
   "title": "Humidity Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT quantile_metric, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Monitoring Data",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT * FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}